name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: v1.31
      run: docker build ./1.31
    - name: v1.33
      run: docker build ./1.33
    - name: v1.34
      run: docker build ./1.34
